### ISSUE TITLE
未提供助力码

### ISSUE THREAD

**Issue by Twinzo1** [sazs34/MyActions#102]
今天早上出现的问题：
日志显示：```由于您secret里面未提供助力码，故此处运行将会给脚本内置的码进行助力，请知晓！```
重新修改助力码，还是不行

**Comment by sazs34** [comment]
哪个脚本

**Comment by hclasmn** [comment]
农场，萌宠都是的，

**Comment by sazs34** [comment]
可以了,作者源调整了下

这边获取一下最新的就行了
