### ISSUE TITLE
京豆变动通知脚本

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#112]
用于统计昨日京豆收支，上游脚本是10点运行，我手机上运行发现脚本运行时间相对较长，建议放在7点运行。
`0 23 * * *`
`https://github.com/lxk0301/scripts/blob/master/jd_bean_change.js `
`https://github.com/lxk0301/scripts/blob/master/.github/workflows/jd_bean_change.yml `

**Comment by sazs34** [comment]
感谢,已添加
