### ISSUE TITLE
免费时常不够怎么设置呢？

### ISSUE THREAD

**Issue by Alexkington** [sazs34/MyActions#113]
20天就要超出Github Action免费使用时长了，请问怎么设置呢

**Comment by MisterGlasses** [comment]
> 20天就要超出Github Action免费使用时长了，请问怎么设置呢

请问在哪看免费时长还有多少

**Comment by goxofy** [comment]
不知道活跃的repo是如何定义的呢

**Comment by Alexkington** [comment]
s

> > 20天就要超出Github Action免费使用时长了，请问怎么设置呢
> 
> 请问在哪看免费时长还有多少

个人设置-Billing & plans

**Comment by meselson** [comment]
你别用私有不就好了，私有项目才占用免费时长
