### ISSUE TITLE
action全被禁用

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#115]
据说fork的项目都被禁用的 复制的项目没事 大佬要不要搞下这个
[repo_sync方式同步lxk0301京东仓库.docx](https://github.com/sazs34/MyActions/files/5462143/repo_sync.lxk0301.docx)

**Comment by sazs34** [comment]
这个成本有点高,先手动开启看看吧

**Comment by MisterGlasses** [comment]
> 这个成本有点高,先手动开启看看吧

现在不知道活跃的定义是什么 我要fork的项目中创建一个随机文件然后删掉 不知道算不算
