### ISSUE TITLE
 This workfow was disabled manually. 

### ISSUE THREAD

**Issue by eromoe** [sazs34/MyActions#116]
原先好好的，今天发现没有执行，上来看了一下
为什么会出现这种情况？
![image](https://user-images.githubusercontent.com/3938751/97654049-18037700-1a9d-11eb-9593-2794f91b71ca.png)

要如何解决

**Comment by sazs34** [comment]
今天所有fork的分支都出了这个问题,先进到actions页面,挨个点Enable吧

观察观察再看

**Comment by eromoe** [comment]
我在 github community 上提了个问题，不知道他们能不能给出原因。整个action disable 掉再开启也无法启动，如果经常发生也很麻烦

**Comment by sandianyue** [comment]
GITHUB推送的邮件里说是60天库不活动自动禁用 这几乎天天都活动 就离谱儿 我觉得是单纯GitHub抽风了😀

**Comment by like-joker** [comment]
一样的问题，所有的工作流都是这样的了，包括其他项目的工作流也是一样的，不晓得是啥子原因，百度不知道，我也看不懂。

**Comment by cikichen** [comment]
一样的，我不止这个，贴吧签到和B站签到都被关了
