### ISSUE TITLE
关于【阅读】模块

### ISSUE THREAD

**Issue by JohnHa0** [sazs34/MyActions#118]
请教大佬一个问题，我是iOS端的，每次运行的时候，阅读那里都提示我从安卓开始，是我没配置好吗？
附上运行结果
2020-11-02 23:08:57
20
20201102
21
今日已过秒数:  83337
22
当前时间戳 1604329737
23
>>>>>>>>>【账号开始】
24

25
【阅读】
26
无法阅读,尝试从安卓端手动开启
27

28
【bubble】
29
暂无有效气泡
30

31
【连续签到】
32

33
同步文件中...
34

35
文件同步完毕, 处理中...
36
HOURS:-1
37
未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
38

**Comment by sazs34** [comment]
仅安卓应用上有入口开启
