### ISSUE TITLE
京东每日签到推送无标题

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#119]
京东签到脚本双账号运行，但是每天只能收到第二个账号的推送，而且推送标题显示为null。
麻烦大佬看下是哪的原因。
![674BBA54-E10A-4908-B55B-F441DF6D38B3](https://user-images.githubusercontent.com/27768847/98453809-4c132200-2198-11eb-8b82-04b6a969d55b.png)

**Comment by MisterGlasses** [comment]
现在第二账号通知会出问题 日志如下。麻烦大佬有空看下。
`https://github.com/MisterGlasses/MyActions/runs/1380806215?check_suite_focus=true `
Bark APP发送通知调用API失败！！
HTTPError: Response code 414 (Request-URI Too Large)
    at Request.<anonymous> (/home/runner/work/MyActions/MyActions/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1605025615953,
    socket: 1605025615954,
    lookup: 1605025615999,
    connect: 1605025616202,
    secureConnect: 1605025616608,
    upload: 1605025616608,
    response: 1605025616810,
    end: 1605025616813,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 45,
      tcp: 203,
      tls: 406,
      request: 0,
      firstByte: 202,
      download: 3,
      total: 860
    }

**Comment by sazs34** [comment]
https://github.com/sazs34/MyActions/commit/59d9f524dd273da9e48d2f0d646652979bb2fb64

已修复

**Comment by MisterGlasses** [comment]
> [59d9f52](https://github.com/sazs34/MyActions/commit/59d9f524dd273da9e48d2f0d646652979bb2fb64)
> 
> 已修复

lxk大佬的签到脚本 通知仍然有问题 bark完全不可用了
`https://github.com/MisterGlasses/JDActions/runs/1396814816?check_suite_focus=true `

**Comment by sazs34** [comment]
Bark的问题，不支持过长的消息推送，推荐切换成TG通知吧
