### ISSUE TITLE
大佬，能在腾讯云函数中签到吗

### ISSUE THREAD

**Issue by lonma** [sazs34/MyActions#12]
大佬，能出个函数脚本不，怕GitHub 2000分钟免费时长不够用

**Comment by sazs34** [comment]
https://docs.github.com/cn/actions/getting-started-with-github-actions/about-github-actions#usage-limits

没看到有2000分钟的限制呀

**Comment by lonma** [comment]
https://docs.github.com/cn/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions下面有个关于github操作的计费，每个月免费时长2000分钟，不知道会不会有满2000分钟的提醒，也没看到具体计时提示（每个操作下是可以看到耗时，但是操作一多起来，不至于自己那么多操作去一个个累加。取消操作但是有邮件提醒耗时）

**Comment by lonma** [comment]
看了下，目前如果jd账号多，比如我跑3个账号，那么腾讯云函数上部署自动签到是免费时长最多的，128M内存，每月免费3200,000秒=888.888小时，调用次数100万次，还有每月免费资源使用量40万GBs，这些应该普通签到，10个账号估计都用不完

**Comment by sazs34** [comment]
暂时不打算做云函数

不过你可以看看

https://github.com/lxk0301/scripts

这位大佬的，他的可以云函数
