### ISSUE TITLE
原作者被删库了

### ISSUE THREAD

**Issue by Twinzo1** [sazs34/MyActions#121]
如题，github库已被删

**Comment by sazs34** [comment]
已更改对应地址

**Comment by sazs34** [comment]
> 已更改对应地址

好像直接改地址还不行，等我看下原因

**Comment by djnwzs** [comment]
> > 已更改对应地址
> 
> 好像直接改地址还不行，等我看下原因

作者加油，等你好消息

**Comment by MisterGlasses** [comment]
> > 已更改对应地址
> 
> 好像直接改地址还不行，等我看下原因

执行异常:HTTPError: Response code 403 (Forbidden)
京东不会是禁了GitHub的ip吧？

**Comment by sazs34** [comment]
> > > 已更改对应地址
> > 
> > 
> > 好像直接改地址还不行，等我看下原因
> 
> 执行异常:HTTPError: Response code 403 (Forbidden)
> 京东不会是禁了GitHub的ip吧？

不是，是github访问gitee被禁掉了

**Comment by MisterGlasses** [comment]
删库原因是滥用action 咱们也低调点吧

**Comment by eromoe** [comment]
![image](https://user-images.githubusercontent.com/3938751/98617566-43f2e800-233a-11eb-80a9-ebf4b72f41ba.png)

这个问题的原因吗

**Comment by sazs34** [comment]
各位，已修复，enjoy~

**Comment by MisterGlasses** [comment]
> 各位，已修复，enjoy~

低调点吧老哥 你是最后的希望了

**Comment by eromoe** [comment]
想问下有没有办法直接出发  pull 插件，只能等时间到吗？

**Comment by sazs34** [comment]
> 想问下有没有办法直接触发 pull 插件，只能等时间到吗？

http://www.ibloger.net/article/3361.html

手动拉取也可以

**Comment by eromoe** [comment]
噢噢，我是怕手动merge 会破坏pull 插件的merge ，没影响我就手动啦
