### ISSUE TITLE
用repo-sync同步会删yml

### ISSUE THREAD

**Issue by qhq** [sazs34/MyActions#127]
请问下如果改用repo-sync方式同步，会删掉本地的yml，权限里设置了不勾workflow也没用。如果您这边最后防止fork，把yml删掉了，一同步本地也就没了，怎么办呢

**Comment by sazs34** [comment]
这个不用担心，我这边不会删除yml
暂时方便切就切过去，不方便的，继续这样也没问题
短期内我这边应该也没有那么多的fork吧

**Comment by qhq** [comment]
好的，谢谢。因为好多secret暂时懒得弄了。出问题再改吧。

**Comment by leecheng311** [comment]
有个想法，不知道对不对，如果我账号a fork你的myaction，账号b再fork我自己账号a的这个项目，是不是能分流掉你原项目的fork数量

**Comment by djnwzs** [comment]
> 请问下如果改用repo-sync方式同步，会删掉本地的yml，权限里设置了不勾workflow也没用。如果您这边最后防止fork，把yml删掉了，一同步本地也就没了，怎么办呢

我这边也不会

**Comment by sazs34** [comment]
https://github.com/sazs34/MyActions/blob/master/backup/reposync.md

这是最新可用的同步说明，可以按照这个进行操作，一次辛苦后续就很轻松啦
