### ISSUE TITLE
通过reposync的方式进行代码同步教程

### ISSUE THREAD

**Issue by tygwd** [sazs34/MyActions#132]
lxk0301大佬的一些代码已经删除，求新的教程以及代码，以便通过reposync的方式进行代码同步

**Comment by hacken156026692** [comment]
同问

**Comment by leoaka** [comment]
> lxk0301大佬的一些代码已经删除，求新的教程以及代码，以便通过reposync的方式进行代码同步

虽然提供的方法本是用来同步lxk0301大佬的，但是可以以此类推同步sazs34的代码呀，只要去相同位置复制sazs34的reposync里的代码就行了 其他步骤一样

**Comment by sazs34** [comment]
https://github.com/sazs34/MyActions/blob/master/backup/reposync.md

更新了说明文档，大家按照这个来就可以，亲测可行

**Comment by byesohu** [comment]
同步完成了，也配置好了cookie、secrets，可是没有可以手动运行的workflow，修改readme也不运行，这是什么原因？

**Comment by sazs34** [comment]
> 同步完成了，也配置好了cookie、secrets，可是没有可以手动运行的workflow，修改readme也不运行，这是什么原因？

https://github.com/byesohu/jddog/blob/main/.github/workflows/repo_sync.yml

看了下,你这边的repo_sync是老的,从https://github.com/sazs34/MyActions/blob/master/.github/workflows/repo-sync.yml 上复制一下,修改一下文件,再执行就可以

具体原因是昨天的repo_sync里面目标分支是master而不是main

**Comment by byesohu** [comment]
我试试，谢谢

**Comment by 09wqlin** [comment]
您好，代码是同步过来，显示的是master跟main两个库是正常的吗？同步过来的代码也没看到在哪里运行了，如何确定他是有效运行呢

**Comment by sazs34** [comment]
> 您好，代码是同步过来，显示的是master跟main两个库是正常的吗？同步过来的代码也没看到在哪里运行了，如何确定他是有效运行呢

你好，我看了下，你这边是同步的lxk0301的repo

这边需要注意的是他的教程文档中有提到吧repo_sync.yml中的`destination_branch`改为`main`
你这边应该是没有改成`main`所以才会有两个分支(创建时默认main,同步后创建了master)

建议按照 https://github.com/sazs34/MyActions/blob/master/backup/reposync.md 
说的一步一步重新操作一下比较OK

**Comment by 09wqlin** [comment]
> > 您好，代码是同步过来，显示的是master跟main两个库是正常的吗？同步过来的代码也没看到在哪里运行了，如何确定他是有效运行呢
> 
> 你好，我看了下，你这边是同步的lxk0301的repo
> 
> 这边需要注意的是他的教程文档中有提到吧repo_sync.yml中的`destination_branch`改为`main`
> 你这边应该是没有改成`main`所以才会有两个分支(创建时默认main,同步后创建了master)
> 
> 建议按照 https://github.com/sazs34/MyActions/blob/master/backup/reposync.md
> 说的一步一步重新操作一下比较OK

更改成master后代码过来了，但是不知道有没有运行，以前更改readme可以让代码运行，现在改了好像没反应？

**Comment by sazs34** [comment]
> > > 您好，代码是同步过来，显示的是master跟main两个库是正常的吗？同步过来的代码也没看到在哪里运行了，如何确定他是有效运行呢
> > 
> > 
> > 你好，我看了下，你这边是同步的lxk0301的repo
> > 这边需要注意的是他的教程文档中有提到吧repo_sync.yml中的`destination_branch`改为`main`
> > 你这边应该是没有改成`main`所以才会有两个分支(创建时默认main,同步后创建了master)
> > 建议按照 https://github.com/sazs34/MyActions/blob/master/backup/reposync.md
> > 说的一步一步重新操作一下比较OK
> 
> 更改成main后代码过来了，但是不知道有没有运行，以前更改readme可以让代码运行，现在改了好像没反应？

**建议按照 https://github.com/sazs34/MyActions/blob/master/backup/reposync.md
说的一步一步重新操作一下比较OK**

麻烦不要再直接改你那个代码了...lxk0301大佬的代码里去掉yaml文件了,不可能定时运行的了
直接用我这边的就行了

**Comment by hlmichael** [comment]
请问一下同步的时候报这个错是为何： Pushing changings from tmp_upstream to origin
remote: Invalid username or password.
fatal: Authentication failed for 。    PAT是应该建在Environment secrets还是Repository secrets下面，怎么调用?

**Comment by hlmichael** [comment]
@sazs34

**Comment by owensbuildex** [comment]
照作也不懂。复制里面的代码，复制哪个？只需复制就行了吗？

**Comment by jimmywinc1** [comment]
大佬 。lxk 那里更新了好多了 啥时候更新呀
