### ISSUE TITLE
reposync同步失败

### ISSUE THREAD

**Issue by wy1ng** [sazs34/MyActions#133]
按教程申请了PAT也添加进PAT了，代码也改成sazs34的reposync的，但是提示失败
  
# File: .github/workflows/repo-sync.yml
name: sync-sazs34-scripts
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-sazs34-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync sazs34-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/sazs34/MyActions.git"
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}

**Comment by wy1ng** [comment]
Run repo-sync/github-sync@v2
/usr/bin/docker run --name ghcrioreposyncgithubsyncv230_1d4800 --label 54bb10 --workdir /github/workspace --rm -e PAT -e INPUT_SOURCE_REPO -e INPUT_SOURCE_BRANCH -e INPUT_DESTINATION_BRANCH -e INPUT_GITHUB_TOKEN -e INPUT_SYNC_TAGS -e GITHUB_TOKEN -e SYNC_TAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/jdsignin/jdsignin":"/github/workspace" ghcr.io/repo-sync/github-sync:v2.3.0  "https://github.com/sazs34/MyActions.git" "master:main"
UPSTREAM_REPO=https://github.com/sazs34/MyActions.git
BRANCHES=master:main
Resetting origin to: ***github.com/wy1ng/jdsignin
Adding tmp_upstream https://github.com/sazs34/MyActions.git
Fetching tmp_upstream
origin	***github.com/wy1ng/jdsignin (fetch)
origin	***github.com/wy1ng/jdsignin (push)
tmp_upstream	https://github.com/sazs34/MyActions.git (fetch)
tmp_upstream	https://github.com/sazs34/MyActions.git (push)
Pushing changings from tmp_upstream to origin
To https://github.com/wy1ng/jdsignin
 ! [remote rejected] tmp_upstream/master -> main (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/jd_818.yaml` without `workflow` scope)
error: failed to push some refs to '***github.com/wy1ng/jdsignin'

**Comment by sazs34** [comment]
https://github.com/maboloshi/Recordum/issues/18

此处需要额外勾选workflow权限, 才能操作.github/workflows/*

**Comment by sazs34** [comment]
网上直接的教程不完善,我这边重新补全一下说明吧

**Comment by sazs34** [comment]
https://github.com/sazs34/MyActions/blob/master/backup/reposync.md

这是最新的说明，按照这个来就行了，感谢您的反馈

**Comment by wy1ng** [comment]
> https://github.com/sazs34/MyActions/blob/master/backup/reposync.md
> 
> 这是最新的说明，按照这个来就行了，感谢您的反馈

搞定了，就是没有勾选workflow的原因。
另外问个弱智问题。。。README.md里为啥我只能写字，不能添加图片。。。
