### ISSUE TITLE
京东每日签到 提示异常

### ISSUE THREAD

**Issue by feng705470052** [sazs34/MyActions#136]
执行异常:Error: Command failed: node execute.js
执行完毕

**Comment by sazs34** [comment]
应该是偶发的，再试试应该OK的

**Comment by Kailic** [comment]
> 应该是偶发的，再试试应该OK的

我也是一样的错误，重试了几下还是这样的错误。

**Comment by feng705470052** [comment]
估计是京东&nbsp;cookie&nbsp;多个换行的问题，我用&amp;区分就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sazs34/MyActions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 下午2:36
收件人:&nbsp;"sazs34/MyActions"<MyActions@noreply.github.com&gt;;
抄送:&nbsp;"┠┧since yearsㄨ"<705470052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sazs34/MyActions] 京东每日签到 提示异常 (#136)





  
应该是偶发的，再试试应该OK的
  
我也是一样的错误，重试了几下还是这样的错误。
