### ISSUE TITLE
前面所有步骤都都做了，最后一步没有run workworkflow

### ISSUE THREAD

**Issue by guiwue** [sazs34/MyActions#139]
一知半解操作，重新操作两边都是最后一步，没有run workworkflow
![D`{M{@ES220TJRG4T%J5QPX](https://user-images.githubusercontent.com/72436973/98893485-7721ac80-24dd-11eb-8193-76e329eb04d6.png)
谢谢解惑。

**Comment by sazs34** [comment]
创建的yml文件没有拷贝我提供的链接里面的内容

**Comment by guiwue** [comment]
![333](https://user-images.githubusercontent.com/72436973/98919509-deedec80-2509-11eb-8f25-0b81d950ee4c.png)
谢谢已经可以了，我开始以为要复制到画圈的里面。
