### ISSUE TITLE
运行种豆得豆时一直在循环替换变量

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#14]
运行种豆得豆时一直在循环替换变量，不知道是不是我的个人原因。日志放在附件了，大佬抽空帮我看一下吧。
![image](https://user-images.githubusercontent.com/27768847/92304516-44c17380-efb1-11ea-8b03-265488106213.png)
[logs_192.zip](https://github.com/sazs34/MyActions/files/5178014/logs_192.zip)

**Comment by sazs34** [comment]
已知问题，拉取一下最新的代码就好啦

**Comment by MisterGlasses** [comment]
多谢大佬

**Comment by MisterGlasses** [comment]
没有更新呀

**Comment by sazs34** [comment]
https://github.com/MisterGlasses/MyActions/runs/1075614275?check_suite_focus=true

刚才看了你最新的执行，已经好了，最新的代码
