### ISSUE TITLE
能否把action的脚本名字换回原本脚本的名字？

### ISSUE THREAD

**Issue by liuning0307** [sazs34/MyActions#142]
改成中文后与lxk0301大佬的脚本不会能一一对应上，不好理解该脚本到底是做什么的。

**Comment by Ouyangchenxing** [comment]
..........................

**Comment by JohnED512** [comment]
> 改成中文后与lxk0301大佬的脚本不会能一一对应上，不好理解该脚本到底是做什么的。

外国友人？

**Comment by sazs34** [comment]
如果想改的话，在自己的分支上改吧
没必要同那边名称一致，大家一眼看过去知道是什么才重要
