### ISSUE TITLE
京东签到不显示账号名字

### ISSUE THREAD

**Issue by Ouyangchenxing** [sazs34/MyActions#143]

**Comment by sazs34** [comment]
这个好像确实有问题，我这边把签到签到lxk0301大佬那边的吧，稍等

**Comment by MisterGlasses** [comment]
> 这个好像确实有问题，我这边把签到签到lxk0301大佬那边的吧，稍等

是不是跟我那个issue是同一个问题？

**Comment by sazs34** [comment]
> > 这个好像确实有问题，我这边把签到签到lxk0301大佬那边的吧，稍等
> 
> 是不是跟我那个issue是同一个问题？

是的是的，已改好
https://github.com/sazs34/MyActions/commit/59d9f524dd273da9e48d2f0d646652979bb2fb64
