### ISSUE TITLE
宠汪汪喂食一天只运行5次吗

### ISSUE THREAD

**Issue by feng705470052** [sazs34/MyActions#145]
感觉次数有点少啊

**Comment by JohnED512** [comment]
> 感觉次数有点少啊

还有，actions明天凌晨1-3点都有空窗期，所有脚本都没j运行计划，宠旺旺的京豆老是抢不到

**Comment by sazs34** [comment]
定时方面不满意，修改自己的就行了

另外，actions不适合于抢东西，执行会延迟十几分钟以上才开始，所以随缘吧

**Comment by MisterGlasses** [comment]
> 感觉次数有点少啊
@feng705470052 @JohnED512 脚本正常执行的话 应该是7次 我这一直没有问题 建议看看自己的喂食action是否正常运行
![104BC8F5-BAFF-4B35-A087-5DC462FC7945](https://user-images.githubusercontent.com/27768847/99073535-08357800-25f1-11eb-95ca-c2832d8deea5.png)
