### ISSUE TITLE
喜马拉雅近期更新

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#150]
望大佬同步更新。
[更新1](https://github.com/Zero-S1/xmly_speed/commit/7eb802c3dd407e887be01efcdea631b0059ec24e) 
1、修改为默认刷时长
2、增加bark通知服务，需要与cookies对应的自定义设备名称，方便查看
3、增加签到，除了第30天
4、修改说明
[更新2](https://github.com/Zero-S1/xmly_speed/commit/80e6a3c5abad0c7d57474d58348fe5b66130cfa6) 
新增签到提醒
[更新3](https://github.com/Zero-S1/xmly_speed/commit/1e76a6b5542e0641523f944237799888c18eb961)
1、增加server酱通知，甚至加了打赏
2、默认读取设备信息，并提供自定义设备命名功能
3、调整参数填写、修改说明

**Comment by sazs34** [comment]
两个通知都加上了
别的功能都已经有了

**Comment by MisterGlasses** [comment]
> 两个通知都加上了
> 别的功能都已经有了

`https://github.com/Zero-S1/xmly_speed/blob/master/xmly_speed.py `
替换代码第51行`notify_time = 19 `可改变通知时间的整点，默认为19:30。
因为喜马拉雅的cron现在为25,55执行，有可能因为延迟通知两次，替换代码第962行`if _notify_time.split()[0] == str(notify_time) and int(_notify_time.split()[1]) > 30: `应该可以解决。
