### ISSUE TITLE
缺失 Secrets，“京喜签到”重复运行

### ISSUE THREAD

**Issue by YM1099** [sazs34/MyActions#154]
### Secrets
其它控制
> `JD_JOY_REWARD_NAME`
> `MARKET_REWARD_NOTIFY`

推送通知专用
> `JD_BEAN_SIGN_STOP_NOTIFY`
> `JD_BEAN_SIGN_NOTIFY_SIMPLE`
> `IGOT_PUSH_KEY`
> `TG_PROXY_HOST`
> `TG_PROXY_PORT`

![image](https://user-images.githubusercontent.com/44107620/99374975-25728b00-28fe-11eb-948e-8924e2c69c33.png)

### 京喜签到
每天运行一次即可 [jd_jingxi.yaml](https://github.com/sazs34/MyActions/blob/master/.github/workflows/jd_jingxi.yaml)
`- cron: "5 0,8,16 * * *"` -> `- cron: "0 9 * * *"`

**Comment by sazs34** [comment]
京喜存在有时无法成功运行的情况，所以多跑几次

**Comment by sazs34** [comment]
其它的明天加一下

**Comment by YM1099** [comment]
好的，感谢^^

**Comment by JohnED512** [comment]
> 其它的明天加一下

大佬我建议增加宠旺旺jd_joy.js每天九点运行一次，因为每天都有宠物赛跑
