### ISSUE TITLE
京东每日签到报错，建议增加提额的运行次数

### ISSUE THREAD

**Issue by JohnED512** [sazs34/MyActions#155]
之前正常签到，今天报错了
![IMG_20201118_015449](https://user-images.githubusercontent.com/55294216/99428266-5de78880-2941-11eb-8018-469bb2b34070.jpg)
京东提额鸭子下蛋速度很快，建议改为10分钟运行一次

**Comment by JasonFeng198** [comment]
我的签到也提示报错了

**Comment by Caiiiiii** [comment]
同样的报错，mark一下

**Comment by 78008495** [comment]
我也报错了，看来不是我个别的问题，大佬麻烦看一下啥原因呀

**Comment by sazs34** [comment]
临时还原到以前的实现了，问题找到了，在考虑怎么还改

**Comment by Walter689** [comment]
同步了大佬最新还原的代码 还是报错

**Comment by sazs34** [comment]
可以了，大家同步一下就行了
