### ISSUE TITLE
京东签到不能用了

### ISSUE THREAD

**Issue by issachigga** [sazs34/MyActions#157]
就是nobyda那个签到好像不能用了 
![屏幕截图 2020-11-18 115652](https://user-images.githubusercontent.com/40743555/99481532-4afea380-2995-11eb-8a38-9c7990b96554.jpg)

**Comment by sazs34** [comment]
更新下

**Comment by sazs34** [comment]
cookie是用换行隔开的还是用的&

**Comment by issachigga** [comment]
> cookie是用换行隔开的还是用的&

换行的

**Comment by sazs34** [comment]
我这边用换行隔开试了下,执行没问题的

1. 确认下代码是不是最新的
2. cookie是不是多了空格
3. 重新运行一次看看

**Comment by issachigga** [comment]
> 我这边用换行隔开试了下,执行没问题的
> 
> 1. 确认下代码是不是最新的
> 2. cookie是不是多了空格
> 3. 重新运行一次看看

换成了&就可以了  谢谢大佬
