### ISSUE TITLE
停止维护了？怎么放到腾讯云函数上啊？执行方法怎么填？默认的index.main_handler报错

### ISSUE THREAD

**Issue by wenshushuVIP** [sazs34/MyActions#158]
代码清空了？怎么放到腾讯云函数上啊？执行方法怎么填？默认的index.main_handler报错

**Comment by sazs34** [comment]
没清空，都在master分支了

参考lxk0301的腾讯云函数布置就好啦

**Comment by sazs34** [comment]
无论原有的fork同步和reposync都不会受影响

**Comment by MisterGlasses** [comment]
> 没清空，都在master分支了
> 
> 参考lxk0301的腾讯云函数布置就好啦

腾讯云函数有什么优点 好用我也转过去

**Comment by sazs34** [comment]
> > 没清空，都在master分支了
> > 参考lxk0301的腾讯云函数布置就好啦
> 
> 腾讯云函数有什么优点 好用我也转过去

优点很多啦

依赖提前安装好的，所以不需要准备，执行很快
这样就可以跑一些类似星推官这种时效性很强的脚本

然后可以直接在线改代码，改完可以直接测试效果，报错也舒服

接着就是Secrets是可以查看的，而不是github里面每次只能全部修改，看不到内容

缺点就是目前定时触发有时没有执行也会显示触发成功了，不过这个可以通过拆分云函数进行

另外一个缺点就是只能有10个定时触发器

**Comment by shusheng110** [comment]
但是云函数签到好像无法操作的啊

**Comment by xicong** [comment]
没腾讯云服务器的就没得完咯，大佬要是能搞个腾讯云脚本和github脚本同步就牛逼咯，两个都能用，😄

**Comment by MisterGlasses** [comment]
腾讯云函数限10个定时器 不太灵活

**Comment by xicong** [comment]
大佬们是不是可以搞个tg群啥的交流下

**Comment by sazs34** [comment]
> 大佬们是不是可以搞个tg群啥的交流下

https://t.me/JD_fruit_pet

lxk0301大佬的tg群,感觉够用了

**Comment by sazs34** [comment]
> 没腾讯云服务器的就没得玩咯，大佬要是能搞个腾讯云脚本和github脚本同步就牛逼咯，两个都能用，😄

不需要腾讯云服务器的，云函数是免费使用的

**Comment by xicong** [comment]
👌，谢谢，我研究下

**Comment by a8992595** [comment]
云函数大佬还会出教程吗

**Comment by sazs34** [comment]
> 云函数大佬还会出教程吗

https://github.com/lxk0301/jd_scripts/wiki/TencentSCF

教程看lxk0301大佬的就够啦

**Comment by xcdeveloper** [comment]
master分支确定不维护了是吧 ？

**Comment by xicong** [comment]
大佬的master分支好像还是一直维护更新的，腾讯云函数是一直同步master分支代码的吗

**Comment by iiiiqt** [comment]
我看了lxk0301大佬的部署到云函数教程 ，其中有二种方法，一种要下载代码到本地，现在仓库空了，不知道怎么下载，另一种通过通过Github Action部署，执行 Action Workflow 进行部署，部署到腾讯云函数脚本找不到。
