### ISSUE TITLE
大佬, 种豆得豆每 3 小时就满了, 但 workflow 是 4 小时执行一次吧

### ISSUE THREAD

**Issue by HenryTSZ** [sazs34/MyActions#160]
我刚开始接触这些, 如果有不对的地方, 还望大佬海涵, 非常感谢

还有就是自动生产营养液是每天 6 点到 21 点, 那运行时间也不对吧

我看别人是这样设置的:

> - cron: '0 23,0-14/1 * * *' #此处为UTC-0时间

**Comment by sazs34** [comment]
好的，时间调整了，另外新增了东东工厂的脚本
