### ISSUE TITLE
寻找能继续维护项目的大佬

### ISSUE THREAD

**Issue by sazs34** [sazs34/MyActions#161]
最近比较忙，同时切到[云函数](https://github.com/lxk0301/jd_scripts/wiki/TencentSCF)去执行了
所以对于项目的维护会比较滞后或者没有维护

目前项目没有什么内容需要调整的
只需要在有新接口来的时候增加个yaml文件即可定期执行

现在寻找一位有时间整理的大佬，将项目转让给你，不要让项目荒废了

**Comment by MisterGlasses** [comment]
有些小问题我能帮着改改 但是不用转给我 我有权限的

**Comment by xcdeveloper** [comment]
> 有些小问题我能帮着改改 但是不用转给我 我有权限的

大佬方便有空同步一下jdFactoryShareCodes.js

**Comment by Choicc** [comment]
> > 有些小问题我能帮着改改 但是不用转给我 我有权限的
> 
> 大佬方便有空同步一下jdFactoryShareCodes.js

已经添加

**Comment by issachigga** [comment]
来留个言支持一下大佬们

**Comment by 282206796** [comment]
感谢大佬辛苦付出

**Comment by aixiaolu** [comment]
大佬怎么加入维护，我想修改一下yaml的时间，现在的时间不对cron用的北京时间，但是action是用世界标准时间的
