### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by xicong** [sazs34/MyActions#164]
![image](https://user-images.githubusercontent.com/11675597/100407760-3bbddb00-30a4-11eb-8f0e-98d0b8a72c1a.png)
昨晚突然所有的都这样咯，不知道怎么处理啊，求助各位大佬啊

**Comment by Choicc** [comment]
github 私人仓库actions每个月是有时间限制的。公开出来就行了。

**Comment by xicong** [comment]
这样呀，谢谢大佬

**Comment by xicong** [comment]
公开是没有限制的吗

**Comment by Choicc** [comment]
> 公开是没有限制的吗

GitHub Actions usage is free for public repositories and self-hosted runners. 目前没有时长限制。
