### ISSUE TITLE
关于东东工厂和惊喜工厂运行时间的建议。

### ISSUE THREAD

**Issue by liuning0307** [sazs34/MyActions#169]
东东工厂免费产生的电力500满，10秒一个电力，84分钟满，所以1一个小时运行一次最好。
京喜工厂免费电力一级二级分别为300和330，所需时间为50分钟和55分钟，考虑到双倍电力的存在，一小时运行一次最好；三级及以后，满电力需要1小时以上，建议运行时间改为20分钟一次，10分钟一次也不是不可以。

**Comment by Choicc** [comment]
由于这两个游戏黑号率比较高,我还是调整为每小时执行一遍吧。已经更新,另外新增了京喜故事。

**Comment by liuning0307** [comment]
黑号这个问题，其实还是跟消费有关，我大号怎么弄都没事，小号京喜工厂还没玩了，自动就黑了。
