### ISSUE TITLE
挂了2天了，没什么动静

### ISSUE THREAD

**Issue by abc799200081** [sazs34/MyActions#18]
所有设置都是一样的，但是actions里面没有任何东西，请问是哪里出了错？

**Comment by sazs34** [comment]
![image](https://user-images.githubusercontent.com/58143504/92844644-aa31bc00-f418-11ea-8d95-d0accf932107.png)

设置允许第三方actions运行了吗

**Comment by abc799200081** [comment]
感谢，现在可以了。

**Comment by zzFelix** [comment]
我的Scheduled 并不会执行，我看了下我的这里也是这个设置啊
允许第三方actions运行，不知道为啥我的就是到实际 不自动执行，点star 手动执行没问题
