### ISSUE TITLE
京喜农场  环境配置错误

### ISSUE THREAD

**Issue by JAXHA** [sazs34/MyActions#181]
==================脚本执行- 北京时间(UTC+8)：12/9/2020, 8:47:21 AM=====================

开始【京东账号1】天使彤彤88

获取任务列表  总共16个任务！

开始第1个任务：签到领现金奖励
{"ret":1032,"retmsg":"err operate env","time":1607474844}

签到领现金奖励[做任务]：err operate env

==============📣系统通知📣==============

**Comment by Choicc** [comment]
现在这个大佬脚本好像只做到双账号，然后种子必须是非app专属的
