### ISSUE TITLE
github action用的是世界标准时，现在的yaml时间参考的是北京时间

### ISSUE THREAD

**Issue by aixiaolu** [sazs34/MyActions#184]
github action用的是世界标准时，现在的yaml时间参考的是北京时间，需要修改一下

**Comment by Choicc** [comment]
现在的时间设置是参照北京事件调整的，是觉得哪个时间有问题呢？

**Comment by aixiaolu** [comment]
> 现在的时间设置是参照北京事件调整的，是觉得哪个时间有问题呢？

重新看了下，之前设置凌晨的跑到7-9点了，是北京时间 ，之前 种豆得豆，萌宠那些都是凌晨运行的

**Comment by aixiaolu** [comment]
> 现在的时间设置是参照北京事件调整的，是觉得哪个时间有问题呢？

早上起来一看没动还以为action出问题了

**Comment by Choicc** [comment]
> > 现在的时间设置是参照北京事件调整的，是觉得哪个时间有问题呢？
> 
> 重新看了下，之前设置凌晨的跑到7-9点了，是北京时间 ，之前 种豆得豆，萌宠那些都是凌晨运行的

除了把一些每天运行一次的整合到多合一，其他的时间是没改的

**Comment by aixiaolu** [comment]
> > > 现在的时间设置是参照北京事件调整的，是觉得哪个时间有问题呢？
> > 
> > 
> > 重新看了下，之前设置凌晨的跑到7-9点了，是北京时间 ，之前 种豆得豆，萌宠那些都是凌晨运行的
> 
> 除了把一些每天运行一次的整合到多合一，其他的时间是没改的

嗯嗯，腾讯云设置不太一样，那边多账号同步有点麻烦，每个任务900s限时，大佬的腾讯云好多是凌晨运行的

**Comment by MisterGlasses** [comment]
除了几个喂食浇水类的脚本外 其它脚本都是尽可能早得运行
