### ISSUE TITLE
宠旺旺喂养次数不够

### ISSUE THREAD

**Issue by aixiaolu** [sazs34/MyActions#187]
现在只有5次喂养，每天要喂7次才能领完奖励，每次加80狗粮，3小时刷新一次

**Comment by MisterGlasses** [comment]
![A5506AC1-2DE5-4BD6-8E9C-F304EBFB4B52](https://user-images.githubusercontent.com/27768847/101727302-33778e00-3aef-11eb-8542-343d57909526.jpeg)
我是每次喂40 一天7次看近几个月的喂食记录 都是喂食7次 建议查看自己的喂食workflow页面 看看是不是少运行或运行错误了

**Comment by MisterGlasses** [comment]
![image](https://user-images.githubusercontent.com/27768847/101727623-c9131d80-3aef-11eb-8fa6-696a7f5ac181.png)
最近wokeflow变动太大 偷狗粮跟喂食脚本运行混了 明天再看看次数吧
