### ISSUE TITLE
种豆得豆支持助力码，新增sharecode文件

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#20]
不好意思老哥，我又来打扰你了😂
lkx0301老哥的种豆脚本更新，支持双账号与sharecode，文件如下，还望抽空更新下
`https://raw.githubusercontent.com/lxk0301/scripts/master/jd_plantBean.js `
`https://github.com/lxk0301/scripts/raw/master/jdPlantBeanShareCodes.js `

**Comment by sazs34** [comment]
已同步修改，感谢您的反馈
