### ISSUE TITLE
请求增加京东直播红包雨jd_live_redrain.js

### ISSUE THREAD

**Issue by aixiaolu** [sazs34/MyActions#200]
请求增加京东直播红包雨jd_live_redrain.js
每天0，9–23单数整点可领，貌似是长期活动

**Comment by aixiaolu** [comment]
https://github.com/lxk0301/jd_scripts/blob/master/jd_live_redrain.js
脚本地址

**Comment by Choicc** [comment]
这个只有活动时间整点5分钟内有,actions延迟比较大,所以这个加进去意义不大
