### ISSUE TITLE
取消自动同步

### ISSUE THREAD

**Issue by q123458384** [sazs34/MyActions#202]
之前用了您的教程自动同步所有fork,现在找不到教程了，不知道怎么自动取消

**Comment by HenryTSZ** [comment]
@q123458384 https://github.com/lxk0301/jd_scripts/blob/master/backUp/gitSync.md

**Comment by q123458384** [comment]
谢谢！

**Comment by kate198909** [comment]
为什么repo拉取不过来 ![image](https://user-images.githubusercontent.com/74090542/102345343-32a39800-3fd8-11eb-9faa-db0ea6775df5.png)

**Comment by q123458384** [comment]
> 为什么repo拉取不过来 ![image](https://user-images.githubusercontent.com/74090542/102345343-32a39800-3fd8-11eb-9faa-db0ea6775df5.png)

看下是否申请了token，secret 里面的 那个key填写了没，

**Comment by kate198909** [comment]
> > 为什么repo拉取不过来 ![image](https://user-images.githubusercontent.com/74090542/102345343-32a39800-3fd8-11eb-9faa-db0ea6775df5.png)
> 
> 
> 
> 看下是否申请了token，secret 里面的 那个key填写了没，
pat肯定填写了呀！不知道为什么！  而且fork过来的act里面没有动作

**Comment by kate198909** [comment]
> > 为什么repo拉取不过来 ![image](https://user-images.githubusercontent.com/74090542/102345343-32a39800-3fd8-11eb-9faa-db0ea6775df5.png)
> 
> 
> 
> 看下是否申请了token，secret 里面的 那个key填写了没，

好了！ md repo里面得pat选项旋转得时候手不小心点掉了一个选项！
