### ISSUE TITLE
喜马拉雅极速版的更新了

### ISSUE THREAD

**Issue by nekomiao123** [sazs34/MyActions#206]
喜马拉雅极速版的原脚本作者进行了更新 希望大佬能及时更新

**Comment by sazs34** [comment]
没有更新啊，在哪里看到更新的呀

**Comment by nekomiao123** [comment]
就是Zero-S1 的仓库里
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/34064940/102376351-84f7af80-3ffe-11eb-8e16-f21430a08088.png">

<img width="949" alt="image" src="https://user-images.githubusercontent.com/34064940/102376451-9c369d00-3ffe-11eb-84e6-41e6fa71fa86.png">

**Comment by sazs34** [comment]
一个月前啊,没有更新
