### ISSUE TITLE
不建议使用jd_unbind

### ISSUE THREAD

**Issue by GSMix** [sazs34/MyActions#220]
会员卡都被自动注销了，事后才发现。里面的积分都没有了。损失还算大。积分可以换礼物。只能事后将此yaml删除。重新注册会员不知道积分还在不在，估计不存在了。

**Comment by Choicc** [comment]
可以添加个secret `UN_BIND_CARD_NUM` 为0 , 就不注销了

**Comment by sazs34** [comment]
移除了，这个有需要的话，手动执行就行
