### ISSUE TITLE
疯狂 joy 挂机脚本运行时间问题

### ISSUE THREAD

**Issue by HenryTSZ** [sazs34/MyActions#222]
大佬, 疯狂 joy 挂机脚本最大只能运行 6 个小时, 到期就自动取消了:

> The job running on runner Hosted Agent has exceeded the maximum execution time of 360 minutes.
> The operation was canceled.

而看视频领奖励是每天晚上和中午 12 点刷新的, 所以是不是要增加一个运行脚本的次数?

**Comment by aixiaolu** [comment]
+1

**Comment by sazs34** [comment]
这个推荐本地node等执行吧，执行时长太长，fork分支的人也快到lxk0301大佬当时被封的数量了
所以不敢过多地执行
