### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by Jankinsu** [sazs34/MyActions#223]
想问一下大家，我想在我的仓库里设置一个自己的workflow不会被同步时覆盖掉，该怎么设置呀

**Comment by siusiu7** [comment]
我明白了 好像是再创建一个新仓库

**Comment by Elletear** [comment]
建立另一个分并将自己的workflow加入该分支

**Comment by Jankinsu** [comment]
> 建立另一个分并将自己的workflow加入该分支

感谢，我试试
