### ISSUE TITLE
店铺取关问题

### ISSUE THREAD

**Issue by 09wqlin** [sazs34/MyActions#226]
按照redme里面设置取关secret，值填的是50,50,,但是脚本运行里面每次只取关20个，是我设置问题还是脚本问题？

**Comment by MisterGlasses** [comment]
我最近的secret设置的参数也失效了

**Comment by sazs34** [comment]
确认下secret名称对不对，好像田征国

**Comment by MisterGlasses** [comment]
> 确认下secret名称对不对，好像田征国

您secret设置的取关参数:

["***"]
是否匹配：：0
取消关注商品---九芝堂足光散40g*5袋/盒足光粉脚气脚...---成功 

看样子secret是可以传进去的 但就是不生效 不知道是不是上游代码变动了

**Comment by 09wqlin** [comment]
> > 确认下secret名称对不对，好像田征国
> 
> 您secret设置的取关参数:
> 
> ["**_"] 是否匹配：：0 取消关注商品---九芝堂足光散40g_5袋/盒足光粉脚气脚...---成功
> 
> 我原来正常 用着用着就发现店铺被清空了 看样子secret是可以传进去的 但就是不生效 不知道是不是上游代码变动了

上游代码变了，具体看下取关脚本的代码，现在每次取关就取消10个好像

**Comment by sazs34** [comment]
> > 确认下secret名称对不对，好像田征国
> 
> 您secret设置的取关参数:
> 
> ["**_"] 是否匹配：：0 取消关注商品---九芝堂足光散40g_5袋/盒足光粉脚气脚...---成功
> 
> 我原来正常 用着用着就发现店铺被清空了 看样子secret是可以传进去的 但就是不生效 不知道是不是上游代码变动了

那就只会是上游的事了哈哈，我这边把特殊的处理去掉了，直接走上游逻辑
