### ISSUE TITLE
疯狂boy挂机时长问题

### ISSUE THREAD

**Issue by chenkid999** [sazs34/MyActions#227]
是否可以将疯狂boy修改为每6小时或者7小时运行一次，我自己仓库改了之后每次同步又会同步回源仓库的数据

**Comment by chenkid999** [comment]
还有就是希望能增加一个单独打印所有助力码的脚本

**Comment by gdracula** [comment]
是时间问题导致的失败吗？同步问题，可以把同步设置30天一次？

**Comment by swvv** [comment]
https://github.com/sazs34/MyActions/issues/222

**Comment by chenkid999** [comment]
> Joy是时间问题导致的失败吗？同步问题，可以把同步设置30天一次？

好办法，我去试试
