### ISSUE TITLE
The job was not started because the spending limit for Actions and Packages has been exceeded.

### ISSUE THREAD

**Issue by asibelieve** [sazs34/MyActions#237]
The job was not started because the spending limit for Actions and Packages has been exceeded.
用了两天就这样，如何解决？
![QQ截图20210106123749](https://user-images.githubusercontent.com/60915972/103729761-19609b00-501c-11eb-9c22-cb9085dd5a5c.png)

**Comment by Choicc** [comment]
私有仓库改为公开。

**Comment by sazs34** [comment]
不要设置为私有仓库，你的所有secrets都不会暴露出来的，放心使用吧

**Comment by asibelieve** [comment]
> 不要设置为私有仓库，你的所有secrets都不会暴露出来的，放心使用吧

谢谢
