### ISSUE TITLE
关于新增的schedule.js

### ISSUE THREAD

**Issue by ycg31** [sazs34/MyActions#238]
这个是为了给京东疯狂joy挂机类脚本用的吗？  保持action一直运行，问题是这个会不会被GitHub判断为滥用action

**Comment by sazs34** [comment]
还真不是给joy挂机用的
现在很多极速版脚本都是要多次运行的,所以直接在action里面实现任务调度,并且再即将超时的时候通过webhook继续唤醒一个新的action来实现的持续任务调度
滥用,肯定会被判定为滥用,想使用的话推荐新开个搞一搞

**Comment by sazs34** [comment]
这个脚本主要解决问题有
1. action无法准时执行，导致需要争分夺秒的兑换类脚本没有意义的情况
2. 需要短时间多次运行的脚本每次都要准备环境安装依赖后才可以运行的情况
3. 脚本运行超时严重，6小时才被动关闭的情况，目前这个脚本执行调度前会关闭之前的子进程

**Comment by ycg31** [comment]
> 这个脚本主要解决问题有
> 
> 1. action无法准时执行，导致需要争分夺秒的兑换类脚本没有意义的情况
> 2. 需要短时间多次运行的脚本每次都要准备环境安装依赖后才可以运行的情况
> 3. 脚本运行超时严重，6小时才被动关闭的情况，目前这个脚本执行调度前会关闭之前的子进程

感谢解答，新开一个是新开库就可以了，还是新注册账号， 一个库有问题会不会连带

**Comment by ycg31** [comment]
lxk0301大佬的脚本增加了京东汽车记分换京豆脚本
#京东汽车积分兑换京豆
cron "0 0 * * *" script-path=https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_car_exchange.js, timeout=2750, wake-system=1, tag=京东汽车积分兑换京豆

**Comment by an0na** [comment]
> lxk0301大佬的脚本增加了京东汽车记分换京豆脚本
> #京东汽车积分兑换京豆
> cron "0 0 * * *" script-path=https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_car_exchange.js, timeout=2750, wake-system=1, tag=京东汽车积分兑换京豆

已经新增上去了，但是action运行有延迟(不能够完全0点准时运行)

**Comment by pansj-dev** [comment]
> > lxk0301大佬的脚本增加了京东汽车记分换京豆脚本
> > #京东汽车积分兑换京豆
> > cron "0 0 * * *" script-path=https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_car_exchange.js, timeout=2750, wake-system=1, tag=京东汽车积分兑换京豆
> 
> 已经新增上去了，但是action运行有延迟(不能够完全0点准时运行)

这个自动任务本来就不是准点，即是国际时间，又有延迟。。。
我有时间看看这个东西怎么玩。。
