### ISSUE TITLE
建立另一个分并将自己的workflow加入该分支

### ISSUE THREAD

**Issue by pxylen** [sazs34/MyActions#243]
建立另一个分并将自己的workflow加入该分支

_Originally posted by @Elletear in https://github.com/sazs34/MyActions/issues/223#issuecomment-752586930_

我创建分支但是action里面没有我的yml任务

**Comment by Elletear** [comment]
需要运行一次才能看到，你可以尝试通过修改时间执行或者手动或者其他可行方式执行。

**Comment by an0na** [comment]
点击一下自己仓库右上角的star（所有的action就开始运行了）
