### ISSUE TITLE
大佬 如何保留自己的task

### ISSUE THREAD

**Issue by jimmywinc1** [sazs34/MyActions#245]
大佬 在别处看到个白条的task 本来已经弄好了 action 一同步就没了 如何 保留呀

**Comment by aixiaolu** [comment]
分享出来让大佬添加，这样同步就不会不在了

**Comment by sazs34** [comment]
单独创建个仓库用于自己想添加的内容就好了

**Comment by jimmywinc1** [comment]
单独创造个仓库 ck 不能通用呀

**Comment by jimmywinc1** [comment]
raw.githubusercontent.com/yangtingxiao/QuantumultX/master/scripts/jd/jd_baiTiao.js

**Comment by jimmywinc1** [comment]
> 单独创建个仓库用于自己想添加的内容就好了

单独创造个 ck 不能通用呀 raw.githubusercontent.com/yangtingxiao/QuantumultX/master/scripts/jd/jd_baiTiao.js
