### ISSUE TITLE
京东脚本可以直接利用lxk0301的jd_get_share_code.js来自动获取互助码

### ISSUE THREAD

**Issue by yxnwh** [sazs34/MyActions#247]
看了大佬你早上新加的内容，应该是自己在运行脚本，访问京东农场、工厂、萌宠等各个子块，然后读取日志内容来获取互助码

其实可以直接执行lxk0301大佬的jd_get_share_code.js，然后直接从运行日志中读取各个邀请码就可以，然后拼接链接提交，搞定！
附上链接地址：https://github.com/lxk0301/jd_scripts/blob/master/jd_get_share_code.js

我不会js，所以具体代码不会写，只能提供一个思路，帮助大佬你简化下工作量！：）

另外，大佬的互助码不太全，附上全部互助码提交的api供大佬使用

京东农场互助码api
http://api.turinglabs.net/api/v1/jd/farm/create/

东东工厂互助码api
http://api.turinglabs.net/api/v1/jd/ddfactory/create/

京喜工厂互助码api
http://api.turinglabs.net/api/v1/jd/jxfactory/create/

种豆得豆互助码api
http://api.turinglabs.net/api/v1/jd/bean/create/

京东萌宠互助码api
http://api.turinglabs.net/api/v1/jd/pet/create/

crazyjoy互助码api（注意，Type后直接拼接互助码）
https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/Type
示例：https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/TypecRxIVdi_PjbiDFQafZkDnQ==

京东赚赚互助码api
https://code.chiang.fun/api/v1/jd/jdzz/create/

**Comment by an0na** [comment]
据我观察，疯狂的joy和京东赚赚的脚本在运行的时候都是会自动提交互助码的，所以这里加不加这两个的自动提交都没有什么意义。

然后就是，大佬写的这个是获取5个活动的互助码后，进行自动提交。
lxk0301大佬的是一键获取到所有活动的互助码，在日志打印方便查看（缺少了一步自动提交的操作）。

这边也没必要去读取lxk0301的脚本日志里面的互助码后，再去自动提交。

使用这个吧，已经能满足你的需求了，并且还是很优秀的。

**Comment by sazs34** [comment]
crazyjoy和京东赚赚自动提交添加了

这个脚本主要不是获取互助码，是提交

省得自己手动提交了

**Comment by yxnwh** [comment]
> 据我观察，疯狂的joy和京东赚赚的脚本在运行的时候都是会自动提交互助码的，所以这里加不加这两个的自动提交都没有什么意义。
> 
> 然后就是，大佬写的这个是获取5个活动的互助码后，进行自动提交。
> lxk0301大佬的是一键获取到所有活动的互助码，在日志打印方便查看（缺少了一步自动提交的操作）。
> 
> 这边也没必要去读取lxk0301的脚本日志里面的互助码后，再去自动提交。
> 
> 使用这个吧，已经能满足你的需求了，并且还是很优秀的。

是的，sazs34大佬的的代码可读性更高，今天重读下sazs34大佬的代码，确实发现在绿色对勾处就已经提交邀请码了，昨天没读懂这块的意思

**Comment by yxnwh** [comment]
> crazyjoy和京东赚赚自动提交添加了
> 
> 这个脚本主要不是获取互助码，是提交
> 
> 省得自己手动提交了

代码小白一个，昨天没太读懂代码意思，见笑了
