### ISSUE TITLE
Secrets文档配置麻烦补充下

### ISSUE THREAD

**Issue by jocccb** [sazs34/MyActions#251]
新更新的feature，没有文档，找代码有些麻烦，麻烦开发者有时间可以补充下，再次谢谢大家。

**Comment by an0na** [comment]
查看【使用教程】中，时效性较快的Secrets配置地址

**Comment by an0na** [comment]
@sazs34 大佬，你看这样是否妥当？我们就不再重复维护Secrets配置了。

**Comment by sazs34** [comment]
> @sazs34 大佬，你看这样是否妥当？我们就不再重复维护Secrets配置了。

棒棒棒
