### ISSUE TITLE
可以同步下企业微信通知的参数吗

### ISSUE THREAD

**Issue by daiqian11234** [sazs34/MyActions#255]
由于多用户推送导致酷推的机器人封禁严重，麻烦作者更新下企业微信推送参数
                  QYWX_KEY: ${{ secrets.QYWX_KEY || github.event.client_payload.QYWX_KEY }}
                  QYWX_AM: ${{ secrets.QYWX_AM || github.event.client_payload.QYWX_AM }}

**Comment by Mortal520** [comment]
+1

**Comment by sazs34** [comment]
已加

**Comment by sazs34** [comment]
可以了
