### ISSUE TITLE
lxk 大佬库没了 

### ISSUE THREAD

**Issue by jimmywinc1** [sazs34/MyActions#258]
lxk 大佬库了 接下去咋整讷

**Comment by jimmywinc1** [comment]
gitee吗

**Comment by Castle1984** [comment]
现在TG上炸了，都在骂用AC的，但是问题是fork的那群人啊，同步库我觉得没有太大问题啊，哎。AC难民，估计都要搬到服务器上了

**Comment by rcfan1** [comment]
的确是没了，我同步的也没了，这可咋怎啊

**Comment by sazs34** [comment]
大家重新同步一波吧
已经切换到gitee上去了

**Comment by ZCY01** [comment]
> 现在TG上炸了，都在骂用AC的，但是问题是fork的那群人啊，同步库我觉得没有太大问题啊，哎。AC难民，估计都要搬到服务器上了

求 tg 链接

**Comment by jimmywinc1** [comment]
现在是在骂在smzdm上发帖子的人 ....

**Comment by hejun041** [comment]
gitee 安全不，有被删的风险没

**Comment by koo9966** [comment]
以前备份了怎么改成自己的地址,老大们

**Comment by bigmax706** [comment]
> 现在是在骂在smzdm上发帖子的人 ....

我都想问一下smzdm骂人的贴在哪，我也想去骂，闷声发大财不好吗

**Comment by sylvia69999** [comment]
gitee链接是？

**Comment by Castle1984** [comment]
> > 现在TG上炸了，都在骂用AC的，但是问题是fork的那群人啊，同步库我觉得没有太大问题啊，哎。AC难民，估计都要搬到服务器上了
> 
> 求 tg 链接

JD_fruit_pet

**Comment by testonlys** [comment]
> 
> 
> > > 现在TG上炸了，都在骂用AC的，但是问题是fork的那群人啊，同步库我觉得没有太大问题啊，哎。AC难民，估计都要搬到服务器上了
> > 
> > 
> > 求 tg 链接
> 
> JD_fruit_pet

找不到这个用户，怎么用这个？

**Comment by dadong1993** [comment]
大佬同步后出现这问题
![2021-01-14-11-51-28](https://user-images.githubusercontent.com/71182539/104542716-0a529c00-565f-11eb-89d6-28ba6db3a9a2.png)
