### ISSUE TITLE
鉴于lxk0301大佬的库又被封了

### ISSUE THREAD

**Issue by sazs34** [sazs34/MyActions#262]
准备停用现有的远程同步机制，改为`git submodule`的方式进行，目的是想不再获取远程了，直接运行的时候取本地的js就好

暂时有这个意向，不过如果这样的话，需要大家在gitee那边也提交ssh才可以

我这边先试试看有没有别的好办法再说吧

有什么想法的可以提一下

**Comment by rokun7** [comment]
大佬搞定了后，给个教程啊，谢谢

**Comment by jimmywinc1** [comment]
大佬 你怎么搞 我跟着...lxk 已经限制ac 运行了 ac gg了

**Comment by jimmywinc1** [comment]
ac 已经运行不了了

**Comment by sazs34** [comment]
坚决拥护lxk0301大佬的决定，哈哈

本项目作废

**Comment by sandianyue** [comment]
。。。危   什么值得买 （x）  什么值得薅 （√）

**Comment by sola237** [comment]
跟着大佬走~希望后面还会有教程~

**Comment by aixiaolu** [comment]
跟着大佬走希望后面还会有教程

**Comment by xiaoyao0081** [comment]
支持

**Comment by 2557558162** [comment]
有后续了吗大佬
