### ISSUE TITLE
京东取消关注关键词

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#28]
不好意思大佬，请问京东取关脚本可以支持下关键词、数量的自定义吗？
目前遇到的问题是，运行取关脚本时，会把自己添加的商品店铺全部取关。
为了解决这个问题，我通过关注apple店铺跟产品来隔来我自己关注的商品
![A038CBD6-90FE-4574-B1B3-FB76A86150F4](https://user-images.githubusercontent.com/27768847/93082869-416e6c00-f6c4-11ea-8abf-fe75bb92f973.png)
，并在boxjs中添加了apple这个关键词
![1B38B28F-9FFD-473A-BB23-4538B4930854](https://user-images.githubusercontent.com/27768847/93082962-619e2b00-f6c4-11ea-8f46-f44b190bb933.png)。
这样，脚本运行时遇到apple就会停止，从而避免取关自己关注的商品。
我看了好久的smartreplace.js，没搞明白该怎么写才能实现，所以大佬抽空能不能支持一下，非常感谢，麻烦了。

**Comment by MisterGlasses** [comment]
`const goodPageSize = $.getdata('jdUnsubscribePageSize') || 0;// 运行一次取消多少个已关注的商品。数字0表示不取关任何商品
const shopPageSize = $.getdata('jdUnsubscribeShopPageSize') || 50;// 运行一次取消多少个已关注的店铺。数字0表示不取关任何店铺
const stop = $.getdata('jdUnsubscribeStopGoods') || '';//遇到此商品不再进行取关，此处内容需去商品详情页（自营处）长按拷贝商品信息
const stopShop = $.getdata('jdUnsubscribeStopShop') || '';//遇到此店铺不再进行取关，此处内容请尽量从头开始输入店铺名称
`
替换这几个关键词应该就可以，但我不会写判断。

**Comment by MisterGlasses** [comment]
主要是关键词 数量调不调的问题不大

**Comment by sazs34** [comment]
好的，明天添加一下

**Comment by MisterGlasses** [comment]
> 好的，明天添加一下

麻烦了老哥

**Comment by sazs34** [comment]
https://github.com/sazs34/MyActions/commit/8cdb710121f4e82fd639e45fbcedffb49688bba8

你好,已支持京东关键字调整,具体配置见首页Secrets说明

**Comment by MisterGlasses** [comment]
> https://github.com/sazs34/MyActions/commit/dab771570ddb086796db437487cc9b0032ae16e0
> 
> 你好,已支持京东关键字调整,具体配置见首页Secrets说明

多谢老哥
