### ISSUE TITLE
云端用户新增设置功能，来控制是否农场和萌宠脚本每次运行后发送通知消息

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#33]
云端用户新增设置功能，来控制是否农场和萌宠脚本每次运行后发送通知消息(其中奖品可兑换通知以及京东cookie失效通知是必须推送通知的，不提供设置)

东东农场脚本 
github action用户填写到Settings-Secrets里面(Name输入 FRUIT_NOTIFY_CONTROL , Value填写true或者false， 其中false打开通知推送，true关闭通知推送)

东东萌宠脚本 
github action用户填写到Settings-Secrets里面(Name输入 PET_NOTIFY_CONTROL , Value填写true或者false， 其中false打开通知推送，true关闭通知推送)

其他云端用户请参考sendNotify.js 说明进行设置

iOS用户可忽略，不影响BoxJs上相应设置的静默运行

**Comment by sazs34** [comment]
嗯，看到了，稍后添加

**Comment by sazs34** [comment]
https://github.com/sazs34/MyActions/commit/56e5836eae9032f9d30b59335b9b291a995d1352

你好，已支持推送通知开关
同时也支持了BARK设置推送通知时的声音

**Comment by MisterGlasses** [comment]
> https://github.com/sazs34/MyActions/commit/56e5836eae9032f9d30b59335b9b291a995d1352
> 
> 你好，已支持推送通知开关
> 同时也支持了BARK设置推送通知时的声音

哈哈感谢
