### ISSUE TITLE
整理了一份脚本cron，大佬请看下。

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#35]
老哥，现在的脚本cron时间有点不太合理，我整理了一份北京时间的脚本运行时间表，左表是按脚本分类，右表是按时间排序，算上延迟同一时间几乎只运行一个脚本，不会容易出错，运行时间感觉也更合理些。我自用了好久了，国际时间cron我也转换好了,如果看着没问题的话我就pr一下。
脚本 | 时间 |   | 脚本 | 时间
-- | -- | -- | -- | --
jd_blueCoin | 0:00 |   | jd_blueCoin | 0:00
jd_daily_bonus | 7:00 |   | jd_joy_feedPets | 0:00
jd_fruit | 8:00 |   | jd_superMarket | 0:10
jd_fruit | 13:00 |   | jd_joy_reward | 0:20
jd_fruit | 17:00 |   | jd_shop | 0:24
jd_joy | 3:20 |   | jd_moneyTree | 2:20
jd_joy | 13:20 |   | jd_speed | 2:30
jd_joy_feedPets | 0:00 |   | jd_joy | 3:20
jd_joy_feedPets | 10:00 |   | jd_superMarket | 4:10
jd_joy_feedPets | 20:00 |   | jd_moneyTree | 5:20
jd_joy_feedPets2 | 6:40 |   | jd_speed | 5:30
jd_joy_feedPets3 | 16:40 |   | jd_joy_steal | 6:00
jd_joy_reward | 0:20 |   | jd_joy_feedPets2 | 6:40
jd_joy_steal | 6:00 |   | jd_daily_bonus | 7:00
jd_joy_steal | 12:00 |   | jd_fruit | 8:00
jd_moneyTree | 2:20 |   | jd_superMarket | 8:10
jd_moneyTree | 5:20 |   | jd_moneyTree | 8:20
jd_moneyTree | 8:20 |   | jd_speed | 8:30
jd_moneyTree | 11:20 |   | jd_pet | 8:40
jd_moneyTree | 14:20 |   | jd_joy_feedPets | 10:00
jd_moneyTree | 17:20 |   | jd_unsubscribe | 11:00
jd_moneyTree | 20:20 |   | jd_moneyTree | 11:20
jd_moneyTree | 23:20 |   | jd_speed | 11:30
jd_pet | 8:40 |   | jd_joy_steal | 12:00
jd_pet | 12:40 |   | jd_superMarket | 12:10
jd_pet | 18:40 |   | jd_pet | 12:40
jd_plantBean | 14:00 |   | jd_fruit | 13:00
jd_plantBean | 18:00 |   | jd_joy | 13:20
jd_plantBean | 22:00 |   | jd_plantBean | 14:00
jd_shop | 0:24 |   | jd_moneyTree | 14:20
jd_speed | 2:30 |   | jd_speed | 14:30
jd_speed | 5:30 |   | jd_unsubscribe | 15:00
jd_speed | 8:30 |   | jd_superMarket | 16:10
jd_speed | 11:30 |   | jd_joy_feedPets3 | 16:40
jd_speed | 14:30 |   | jd_fruit | 17:00
jd_speed | 17:30 |   | jd_moneyTree | 17:20
jd_speed | 20:30 |   | jd_speed | 17:30
jd_speed | 23:30 |   | jd_plantBean | 18:00
jd_superMarket | 0:10 |   | jd_pet | 18:40
jd_superMarket | 4:10 |   | jd_unsubscribe | 19:00
jd_superMarket | 8:10 |   | jd_joy_feedPets | 20:00
jd_superMarket | 12:10 |   | jd_superMarket | 20:10
jd_superMarket | 16:10 |   | jd_moneyTree | 20:20
jd_superMarket | 20:10 |   | jd_speed | 20:30
jd_unsubscribe | 11:00 |   | jd_plantBean | 22:00
jd_unsubscribe | 15:00 |   | jd_moneyTree | 23:20
jd_unsubscribe | 19:00 |   | jd_speed | 23:30

**Comment by MisterGlasses** [comment]
其中，取关脚本如果一次取关过多，可能会出问题，所以分三次取关。
签到脚本默认有通知，不宜在半夜运行。

**Comment by sazs34** [comment]
> 其中，取关脚本如果一次取关过多，可能会出问题，所以分三次取关。
> 签到脚本默认有通知，不宜在半夜运行。

哈哈哈，非常感谢，麻烦pr一下

**Comment by MisterGlasses** [comment]
> > 其中，取关脚本如果一次取关过多，可能会出问题，所以分三次取关。
> > 签到脚本默认有通知，不宜在半夜运行。
> 
> 哈哈哈，非常感谢，麻烦pr一下

不要客气老哥，我也是为了以后同步脚本时省事。

**Comment by MisterGlasses** [comment]
已pr，大佬请验收。
