### ISSUE TITLE
现有的手动触发方式属于太阳能手电筒

### ISSUE THREAD

**Issue by goukey** [sazs34/MyActions#38]
现有的`workflow_dispatch:`触发方式有个很大的问题，run选项只有在此任务运行过之后才会出现，对于第一次fork过去的用户来说，workflow界面一片空白，如何让人去点击run？

所以还是star触发的方式比较可行。

每个yml都添加
`    watch:
        types: [started]`
即可.

**Comment by MisterGlasses** [comment]
感觉脚本运行出错时重新运行时有用，第一次fork之后不能定时触发吗？

**Comment by goukey** [comment]
很多时候都不能，action偶尔会需要你手动先运行一次。
