### ISSUE TITLE
pull.yml文件内默认为merge

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#47]
现在又改成情况1了。上游仓库中的pull.yml文件内默认为merge，如果下游自己将pull.yml文件改为hardreset，则在一次pull之后又被上游覆盖为merge。

**Comment by sazs34** [comment]
那默认hardreset就好了,下游自己改为merge就没问题哈
我这边调整一下

**Comment by MisterGlasses** [comment]
read.me别忘了同步改下

**Comment by sazs34** [comment]
已调整,README也改了~

**Comment by MisterGlasses** [comment]
![image](https://user-images.githubusercontent.com/27768847/93853587-af2f1f00-fce6-11ea-835c-a429d4250ba1.png)
老哥我咨询个事 这个匿名提交是怎么搞的 有教程吗 我想学一下 Google没搜到东西

**Comment by MisterGlasses** [comment]
`方案A - 强制远程分支覆盖自己的分支
参考这里，安装pull插件，并确认此项目已在pull插件的作用下（参考文中1-d）。
确保.github/pull.yml文件正常存在，yml内上游作者填写正确(此项目已填好，无需更改)。
确保pull.yml里面是mergeMethod: merge(默认就是merge)。
ENJOY!上游更改三小时左右就会自动发起同步。`
这地方出错了 
`确保pull.yml里面是mergeMethod: hardreset(默认就是hardreset)。`
