### ISSUE TITLE
宠汪汪喂食默认喂10g京小超默认不兑换

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#5]
宠汪汪喂食默认喂10g京小超默认不兑换，大佬可以加个相应替换吗？

**Comment by sazs34** [comment]
https://github.com/sazs34/MyActions/commit/2ca101f0feb2a3b03ea59fa2ab2046f2a7cc5e82
已支持，具体使用见readme

按照http://www.ibloger.net/article/3361.html 拉取下最新的代码到您已fork的分支即可
