### ISSUE TITLE
Actions到时间不自动执行

### ISSUE THREAD

**Issue by zzFelix** [sazs34/MyActions#50]
![image](https://user-images.githubusercontent.com/58143504/92844644-aa31bc00-f418-11ea-8d95-d0accf932107.png)

设置允许第三方actions运行了吗

_Originally posted by @sazs34 in https://github.com/sazs34/MyActions/issues/18#issuecomment-690833831_

我的Scheduled 并不会执行，我看了下我的设置 已经是
允许第三方actions运行，不知道为啥我的就是到实际 不自动执行，点star 手动执行没问题

我尝试过删除 重新fork，还是不行

**Comment by sazs34** [comment]
亲自fork了个看下,确实不行,我这边查下问题

**Comment by goukey** [comment]
github action本身抽风的问题，经常是只有你手动运行过一次以后它才会激活。
如果去掉了star执行，又怎么去手动执行呢？

**Comment by singer1026** [comment]
上面提问的是我朋友，他的仓库 我让他删除了一个yaml文件  然后随便在一个文件加了个空行，然后再提交  隔了几分钟发现就能自动运行了！  很是奇怪

**Comment by sazs34** [comment]
你好，FORK后，如果actions没有定时执行，请随便找个文件，加个空格提交一下，就应该可以正常执行了

**Comment by sazs34** [comment]
> 上面提问的是我朋友，他的仓库 我让他删除了一个yaml文件 然后随便在一个文件加了个空行，然后再提交 隔了几分钟发现就能自动运行了！ 很是奇怪

是的，我这边测试了下确实改个文件里面加个空格就行了
