### ISSUE TITLE
Cookie提示失效

### ISSUE THREAD

**Issue by lonma** [sazs34/MyActions#51]
Cookie提示失效，但用lack0301脚本是有效的，不知道是只有我一个人遇到这个问题不。

**Comment by sazs34** [comment]
是全部提示失效还是哪一个提示失效?

**Comment by lonma** [comment]
> 是全部提示失效还是哪一个提示失效?

只有摇钱树的是正常执行完毕。其他的都报错，cookie失效。之前一直以为是三个cookie 同时更新，会导致另外两个失效，后面索性只填一个cookie，还是失效。lxk0301的脚本里也是同一个cookie ，执行正常。

**Comment by sazs34** [comment]
> > 是全部提示失效还是哪一个提示失效?
> 
> 只有摇钱树的是正常执行完毕。其他的都报错，cookie失效。之前一直以为是三个cookie 同时更新，会导致另外两个失效，后面索性只填一个cookie，还是失效。lxk0301的脚本里也是同一个cookie ，执行正常。

查看了下其它fork的action执行，并没有发现出问题

如果可以的话，麻烦将JD_COOKIE关键部分打码然后截图发来看下。

**Comment by lonma** [comment]
![Uploading 6D5FF41B-1C0E-465D-8379-D530341C7EBB.png…]()

**Comment by lonma** [comment]
![1392C93B-47D5-4349-84AC-45822D3B7A5C](https://user-images.githubusercontent.com/13904070/94327945-40e9a580-ffe1-11ea-898a-e97ae8b3bc35.png)
![015E2575-220C-4B48-AF1D-920E0D021233](https://user-images.githubusercontent.com/13904070/94327946-421ad280-ffe1-11ea-92bf-65df838622e3.png)
![AF367616-31E0-4C98-85EB-7B86EBB79B6C](https://user-images.githubusercontent.com/13904070/94327947-434bff80-ffe1-11ea-8fff-4a6932c6232e.png)
![81A0473F-4D48-4F75-9823-95214E9AE80F](https://user-images.githubusercontent.com/13904070/94327948-447d2c80-ffe1-11ea-8157-04ebf98b0ece.png)


> > > 是全部提示失效还是哪一个提示失效?
> > 
> > 
> > 只有摇钱树的是正常执行完毕。其他的都报错，cookie失效。之前一直以为是三个cookie 同时更新，会导致另外两个失效，后面索性只填一个cookie，还是失效。lxk0301的脚本里也是同一个cookie ，执行正常。
> 
> 查看了下其它fork的action执行，并没有发现出问题
> 
> 如果可以的话，麻烦将JD_COOKIE关键部分打码然后截图发来看下。

![3B0AF657-8FA9-42D7-AC5F-DB0071434E61](https://user-images.githubusercontent.com/13904070/94327962-65458200-ffe1-11ea-9151-7b327c4e8c8c.png)
![790518F1-49D0-491E-AC46-D2A49F901132](https://user-images.githubusercontent.com/13904070/94327967-6b3b6300-ffe1-11ea-8313-729a142d41c3.png)
![C85FA7F4-E7C3-4F8B-BA4B-DA87DCE0F1DE](https://user-images.githubusercontent.com/13904070/94327968-6bd3f980-ffe1-11ea-9ad0-c3ec7dc56f99.png)
![AF505637-87E4-4F22-A2EB-1AA912DB3EE9](https://user-images.githubusercontent.com/13904070/94327969-6d052680-ffe1-11ea-8184-9057e63ff200.png)
![EB6AE537-C1D5-4197-9FCC-943059AA7110](https://user-images.githubusercontent.com/13904070/94327970-6d9dbd00-ffe1-11ea-9002-6c028ba7a47c.png)

**Comment by sazs34** [comment]
不是这个,是京东cookie...
pt_key=4dq*******;pt_pin=g2123f*****231;&pt_key=4dq*******;pt_pin=g2123f*****231;&pt_key=4dq*******;pt_pin=g2123f*****231;
三个账号嘛，你把这块给我下，pt_key和pt_pin里面的你随便删一些添加一些内容然后发来

估计是你cookie的问题

**Comment by lonma** [comment]
> 不是这个,是京东cookie...
> pt_key=4dq*******;pt_pin=g2123f_****231;&pt_key=4dq*******;pt_pin=g2123f****_231;&pt_key=4dq*******;pt_pin=g2123f*****231;
> 三个账号嘛，你把这块给我下，pt_key和pt_pin里面的你随便删一些添加一些内容然后发来
> 
> 估计是你cookie的问题

pt_key=AA******abcd;pt_pin=wd*****abcd;&pt_key=AA*********abcd; pt_pin=3******abcd;&pt_key=A*******_abcd; pt_pin=l**abcd;

**Comment by sazs34** [comment]
pt_key=AAabcd;pt_pin=wdabcd;&pt_key=AAabcd; pt_pin=3abcd;&pt_key=A*****_abcd; pt_pin=l**abcd;

pt_pin前面不要有空格，否则在env.js中会报错

**Comment by lonma** [comment]
好的，感谢大佬
