### ISSUE TITLE
电信签到脚本

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#54]
不好意思老哥，我又来麻烦你了，希望能添加一下[电信签到脚本](https://github.com/chavyleung/scripts/tree/master/10000)。
对应的[BoxJS订阅](https://github.com/chavyleung/scripts/blob/master/box/chavy.boxjs.json)
电信签到脚本的签到功能只需要传入一个电信手机号，基本不会存在失效问题。
`$.KEY_mobile = 'chavy_mobile_10000'`
该脚本还有一个查询当前积分的功能，这个需要cookie，会失效，但失效后好像不会影响签到功能。
`$.KEY_signbody = 'chavy_signbody_10000'`
考虑到电信经常系统维护，放在每天7:30执行较好。
`30 23 * * *`
此外，联通签到脚本cookie经常失效，没必要做。

**Comment by sazs34** [comment]
准备写一个通用的，到时就很舒服了

**Comment by MisterGlasses** [comment]
> 准备写一个通用的，到时就很舒服了

其它的脚本如果没有cookie失效通知，不好整啊，比如我很想要个爱奇艺签到action，但野比大佬的原脚本不支持server跟bark,失效了也不知道，就这个电信签到只需要一个手机号就能完成基本的签到任务。

**Comment by sazs34** [comment]
> 建议增加其它脚本时新建一个项目 现在这个里边脚本太多啦 而且可能有脚本用不到

哈哈，目前还行，只有京东的脚本，外加一个喜马拉雅的
全是氪金脚本

**Comment by MisterGlasses** [comment]
> > 建议增加其它脚本时新建一个项目 现在这个里边脚本太多啦 而且可能有脚本用不到
> 
> 哈哈，目前还行，只有京东的脚本，外加一个喜马拉雅的
> 全是氪金脚本

后期再加新脚本的话建议新开一个 现在这个脚本运行得太挤了 此外 我觉得京东摇钱树脚本可以撤掉了 没什么搞头啥也换不了 一天还执行那么多遍

**Comment by MisterGlasses** [comment]
能换的东西太虚了![3AF3214A-F2B3-4509-BA76-511FC9AB0439](https://user-images.githubusercontent.com/27768847/95878753-2452b900-0da8-11eb-9622-8e0c4acf8d88.png)
![A31BAE04-FB02-4387-81E9-DAAA35973311](https://user-images.githubusercontent.com/27768847/95878768-27e64000-0da8-11eb-813d-5cfed30595e0.png)

**Comment by sazs34** [comment]
暂时不准备新增非薅羊毛类的脚本签到
