### ISSUE TITLE
喜码拉雅自定义user agent

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#60]
大佬[喜马拉雅脚本](https://github.com/Zero-S1/xmly_speed/blob/master/xmly_speed.py)中第30行有个user agent需要修改，以便于使用安卓机上的cookie，可以在smartreplace.js中支持一下吗？
`UserAgent = "Mozilla/5.0 (Linux; Android 7.0; KNT-UL10 Build/HUAWEIKNT-UL10) AppleWebKit/537.36 (KHTML, like Gecko) ting_1.8.30(KNT-UL10,Android24)"
# 非iOS设备的需要的自行修改,自己抓包 与cookie形式类似
`

**Comment by sazs34** [comment]
好的，这两天搞一下

**Comment by MisterGlasses** [comment]
麻烦了

**Comment by sazs34** [comment]
https://github.com/sazs34/MyActions/commit/d3f04db2236adf3f22083229919df6ad8d689576

已支持

**Comment by MisterGlasses** [comment]
> [d3f04db](https://github.com/sazs34/MyActions/commit/d3f04db2236adf3f22083229919df6ad8d689576)
> 
> 已支持

多谢老哥
