### ISSUE TITLE
爱奇艺签到脚本

### ISSUE THREAD

**Issue by lonma** [sazs34/MyActions#62]
https://github.com/BlueskyClouds/iQIYI-DailyBonus
原作者这个cookie获取方式暂时没看懂，希望大佬能够添加个爱奇艺的签到，感谢（能完善下cookie获取方式就更好了）

**Comment by BlueskyClouds** [comment]
这么简单的获取方式... 就取其中的P00001值就行了。

**Comment by MisterGlasses** [comment]
> 这么简单的获取方式... 就取其中的P00001值就行了。

我按教程也获取不到 点开个人中心才找到的

**Comment by lonma** [comment]
> 这么简单的获取方式... 就取其中的P00001值就行了。

好的谢谢大佬。大佬，能出个腾讯视频的action 么

**Comment by lonma** [comment]
> 这么简单的获取方式... 就取其中的P00001值就行了。

大佬，想问下serverchan可以设置成cookie失效才推送通知么？

**Comment by MisterGlasses** [comment]
> > 这么简单的获取方式... 就取其中的P00001值就行了。
> 
> 大佬，想问下serverchan可以设置成cookie失效才推送通知么？

同问

**Comment by BlueskyClouds** [comment]
> > 这么简单的获取方式...就取其中的P00001值就行了。
> 
> 大佬，想问下serverchan可以设置成Cookie重新才按下通知么？

给你提交PR了 合并一下就行了，

**Comment by lonma** [comment]
> > > 这么简单的获取方式...就取其中的P00001值就行了。
> > 
> > 
> > 大佬，想问下serverchan可以设置成Cookie重新才按下通知么？
> 
> 给你提交PR了 合并一下就行了，

大佬，腾讯视频视频签到有用么，能否出个action自动签到

**Comment by lonma** [comment]
> > > 这么简单的获取方式...就取其中的P00001值就行了。
> > 
> > 
> > 大佬，想问下serverchan可以设置成Cookie重新才按下通知么？
> 
> 给你提交PR了 合并一下就行了，
大佬 这个提示算正常不？
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
added 159 packages from 97 contributors and audited 159 packages in 5.147s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

爱奇艺签到-爱奇艺-查询失败: 无到期数据 ⚠️ 
爱奇艺-签到失败: 今日已签到 ⚠️ 
爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (1) 
爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (2) 
爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (3)

**Comment by MisterGlasses** [comment]
> > > > 这么简单的获取方式...就取其中的P00001值就行了。
> > > 
> > > 
> > > 大佬，想问下serverchan可以设置成Cookie重新才按下通知么？
> > 
> > 
> > 给你提交PR了 合并一下就行了，
> > 大佬 这个提示算正常不？
> > npm WARN deprecated request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142)
> > npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> > npm notice created a lockfile as package-lock.json. You should commit this file.
> > added 159 packages from 97 contributors and audited 159 packages in 5.147s
> 
> 1 package is looking for funding
> run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> 爱奇艺签到-爱奇艺-查询失败: 无到期数据 ⚠️
> 爱奇艺-签到失败: 今日已签到 ⚠️
> 爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (1)
> 爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (2)
> 爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (3)

建议去作者那提issue

**Comment by sazs34** [comment]
暂时不准备新增非薅羊毛类的脚本签到
