### ISSUE TITLE
京东农场支持多账号 多了FruitShareCodes这个secret

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#7]
京东农场支持多账号 多了FruitShareCodes这个secret，大佬的lxk0301.js脚本需要改吗

**Comment by MisterGlasses** [comment]
实测运行出错
`Run node lxk0301_old.js
当前共2个账号需要签到
下载代码完毕
正在执行第1个账号签到任务
替换变量完毕
开始获取配置文件


🔔东东农场, 开始!

❌ 东东农场, 失败! 原因: Error: Cannot find module './sendNotify'!


🔔东东农场, 结束! 🕛 0.004 秒
执行完毕
正在执行第2个账号签到任务
替换变量完毕
开始获取配置文件


🔔东东农场, 开始!

❌ 东东农场, 失败! 原因: Error: Cannot find module './sendNotify'!


🔔东东农场, 结束! 🕛 0.004 秒
执行完毕
全部执行完毕`

**Comment by sazs34** [comment]
[7db3718](https://github.com/sazs34/MyActions/commit/7db371829a9db7f1831c78037925a1b7c852d6b1) 已修复相关问题
同时也已支持FruitShareCodes

按照http://www.ibloger.net/article/3361.html 拉取下最新的代码到您已fork的分支即可

**Comment by sazs34** [comment]
> 实测运行出错
> `Run node lxk0301_old.js
> 当前共2个账号需要签到
> 下载代码完毕
> 正在执行第1个账号签到任务
> 替换变量完毕
> 开始获取配置文件
> 
> 🔔东东农场, 开始!
> 
> ❌ 东东农场, 失败! 原因: Error: Cannot find module './sendNotify'!
> 
> 🔔东东农场, 结束! 🕛 0.004 秒
> 执行完毕
> 正在执行第2个账号签到任务
> 替换变量完毕
> 开始获取配置文件
> 
> 🔔东东农场, 开始!
> 
> ❌ 东东农场, 失败! 原因: Error: Cannot find module './sendNotify'!
> 
> 🔔东东农场, 结束! 🕛 0.004 秒
> 执行完毕
> 全部执行完毕`

感谢您及时反馈报错

**Comment by MisterGlasses** [comment]
感谢大佬
