### ISSUE TITLE
secrect好像搞乱套了

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#70]
jd_joy.yaml 里是 JDJoyFeedCount: ${{ secrets.JDJoyFeedCount }}
jd_joy_feedPets.yaml jd_joy_feedPets2.yaml里是 JOY_FEED_COUNT: ${{ secrets.JOY_FEED_COUNT }} 和 JDJoyFeedCount: ${{ secrets.JDJoyFeedCount }}
jd_blueCoin.yaml 里是 JDMarketCoinToBeans: ${{ secrets.JDMarketCoinToBeans }}
与read.me中的secrect对不起来，不知道该用哪个了。

**Comment by sazs34** [comment]
已修复，完全同步了lxk0301的
