### ISSUE TITLE
京喜签到错误

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#74]
❗️京喜, 错误!
ReferenceError: doubleres is not defined
at/home/runner/work/MyActions/MyActions/execute.js:196:24
at new Promise (<anonymous>)
atshowmsg(/home/runner/work/MyActions/MyActions/execute.js:193:10)
at/home/runner/work/MyActions/MyActions/execute.js:43:13
at processTicksAndRejections (internal/process/task_queues.js:97:5)
完整日志如下
`https://github.com/MisterGlasses/MyActions/runs/1254608963?check_suite_focus=true `

**Comment by sazs34** [comment]
这个是会偶尔报错，不过看过处理过程可，这个报错是在执行完毕，准备通知时才报错的，实际执行已经成功了
所以不用理会
