### ISSUE TITLE
京小超失败

### ISSUE THREAD

**Issue by lion-goose** [sazs34/MyActions#81]
京小超连续失败，好像是找不到分享码的js

**Comment by MisterGlasses** [comment]
京小超, 失败! 原因: Error: Cannot find module './jdSuperMarketShareCodes.js'

**Comment by Naughty-Monkey** [comment]
京小超, 失败! 原因: Error: Cannot find module './jdSuperMarketShareCodes.js'!

**Comment by sazs34** [comment]
感谢反馈，问题已修复，请同步一下代码即可
