### ISSUE TITLE
京小超还是有问题

### ISSUE THREAD

**Issue by lion-goose** [sazs34/MyActions#82]
![AC5A3357-3E75-4376-92A9-FC06E35DAA3F](https://user-images.githubusercontent.com/59443350/96357205-79d1f180-112b-11eb-8c96-4e6675eab346.png)

Cannot find module './jdSuperMarketShareCodes.js'!

是不是这个js在原代码里是直接本地引用，所以也需要把这个文件同步过来

**Comment by goukey** [comment]
需要把jdSuperMarketShareCodes.js同步过来，在onlyOneExecute.js里加一条变量？

**Comment by sazs34** [comment]
手动执行看下，我看你action是两小时前运行的，我代码是一小时前提交的

**Comment by goukey** [comment]
确实有这个问题，需要同步js

**Comment by sazs34** [comment]
> 需要把jdSuperMarketShareCodes.js同步过来，在onlyOneExecute.js里加一条变量？

不用，运行时会文件过来，变量也不用加，只要yaml中配置了就可以了

**Comment by goukey** [comment]
手动又成功了..........

**Comment by sazs34** [comment]
> 手动又成功了..........

不是手动自动的问题，是两小时前我的新代码压根没提交

**Comment by sazs34** [comment]
![Uploading DEAADCCE-45AC-4A5C-B9A7-FB1FFEC30E5C.png…]()

**Comment by sazs34** [comment]
![57144245-1399-4523-A82D-A293314A284A](https://user-images.githubusercontent.com/58143504/96357568-2f9f3f00-1130-11eb-90ab-012e06c02677.png)

**Comment by lion-goose** [comment]
谢谢大佬答疑，直接re-run job确实不行，重新跑一遍脚本就好了！

**Comment by sazs34** [comment]
确保任务是在9:34分之后执行且代码已同步过的
