### ISSUE TITLE
京喜可以仅在cookie失效后通知吗

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#87]
大佬 目前每个京东账号一天都会推送三次通知
![39659EDE-FFF8-439B-92A0-31C2DEE24FE6](https://user-images.githubusercontent.com/27768847/96561158-c7985680-12f1-11eb-83f2-05e90fe00e07.png)

**Comment by sazs34** [comment]
京喜为了防止执行失败，改为一天执行三次了

**Comment by MisterGlasses** [comment]
> 京喜为了防止执行失败，改为一天执行三次了

原来不是lxk0301的脚本 怪不得每次脚本运行都有通知
