### ISSUE TITLE
[new secrete]关于xmly指定时间开启刷时长

### ISSUE THREAD

**Issue by sandianyue** [sazs34/MyActions#88]
带佬 你觉得是否有必要 进一步加入自定义xmly刷时长开启/关闭的功能  :)
目的解决就是现在时长刷的太离谱儿了 24h刷.... 少刷一点 低调些 答题还好 这个刷时长本地都没播放记录的... 真就直接上传时长...少刷点“混入其中”....
想法就是再加入一个secrete 仓库根目录下的xmly_speed.py先通过date判断当前小时是否属于secrete变量中的 不属于就XMLY_ACCUMULATE_INDEX加上该账号云云 
或者直接与判断来控制XMLY_ACCUMULATE_TIME？

**Comment by sazs34** [comment]
好主意，已支持自定义执行时长https://github.com/sazs34/MyActions/commit/3ef206aef3d5ac083ba5613ac65a35dfec460166

具体配置方法请看[喜马拉雅Secrets配置](https://github.com/sazs34/MyActions#%E5%96%9C%E9%A9%AC%E6%8B%89%E9%9B%85%E4%B8%93%E7%94%A8)

**Comment by sandianyue** [comment]
> 好主意，已支持自定义执行时长[3ef206a](https://github.com/sazs34/MyActions/commit/3ef206aef3d5ac083ba5613ac65a35dfec460166)
> 
> 具体配置方法请看[喜马拉雅Secrets配置](https://github.com/sazs34/MyActions#%E5%96%9C%E9%A9%AC%E6%8B%89%E9%9B%85%E4%B8%93%E7%94%A8)

好的 感谢带佬 👍
