### ISSUE TITLE
喜马拉雅出错

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#89]
同步文件中...
文件同步完毕, 处理中...
HOURS:-1
未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
Traceback (most recent call last):
  File "xmly_speed.py", line 86, in <module>
    run()
  File "xmly_speed.py", line 78, in run
    if isJumpIndex(idx+1):
  File "xmly_speed.py", line 47, in isJumpIndex
    xmly_accumulate_index = [int(i) for i in indexLimit.split(",")]
  File "xmly_speed.py", line 47, in <listcomp>
    xmly_accumulate_index = [int(i) for i in indexLimit.split(",")]
ValueError: invalid literal for int() with base 10: ''
Error: Process completed with exit code 1.

**Comment by sazs34** [comment]
感谢报错，已修复

**Comment by MisterGlasses** [comment]
> 感谢报错，已修复
大佬第二账号不执行 麻烦看下
https://github.com/MisterGlasses/MyActions/runs/1285954385?check_suite_focus=true

**Comment by MisterGlasses** [comment]
> > 感谢报错，已修复
> > 大佬第二账号不执行 麻烦看下
> > https://github.com/MisterGlasses/MyActions/runs/1285954385?check_suite_focus=true

File "./execute1.py", line 44
    ***
                      ^
SyntaxError: invalid syntax

同步文件中...

文件同步完毕, 处理中...
HOURS:-1
未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
HOURS:-1
未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制

***************************
文件全部执行完毕

**Comment by sazs34** [comment]
> > > 感谢报错，已修复
> > > 大佬第二账号不执行 麻烦看下
> > > https://github.com/MisterGlasses/MyActions/runs/1285954385?check_suite_focus=true
> 
> File "./execute1.py", line 44
> ***
> ^
> SyntaxError: invalid syntax
> 
> 同步文件中...
> 
> 文件同步完毕, 处理中...
> HOURS:-1
> 未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
> HOURS:-1
> 未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
> 
> 文件全部执行完毕

麻烦将自定义的agent发我看下

**Comment by MisterGlasses** [comment]
> > > > 感谢报错，已修复
> > > > 大佬第二账号不执行 麻烦看下
> > > > https://github.com/MisterGlasses/MyActions/runs/1285954385?check_suite_focus=true
> > 
> > 
> > File "./execute1.py", line 44
> > 
> > ^
> > SyntaxError: invalid syntax
> > 同步文件中...
> > 文件同步完毕, 处理中...
> > HOURS:-1
> > 未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
> > HOURS:-1
> > 未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
> > 文件全部执行完毕
> 
> 麻烦将自定义的agent发我看下

`Mozilla/5.0 (Linux; Android 7.0; KNT-UL10 Build/HUAWEIKNT-UL10) AppleWebKit/537.36 (KHTML, like Gecko) ting_1.8.30(KNT-UL10,Android24)`

**Comment by sazs34** [comment]
> > > > > 感谢报错，已修复
> > > > > 大佬第二账号不执行 麻烦看下
> > > > > https://github.com/MisterGlasses/MyActions/runs/1285954385?check_suite_focus=true
> > > 
> > > 
> > > File "./execute1.py", line 44
> > > ^
> > > SyntaxError: invalid syntax
> > > 同步文件中...
> > > 文件同步完毕, 处理中...
> > > HOURS:-1
> > > 未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
> > > HOURS:-1
> > > 未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
> > > 文件全部执行完毕
> > 
> > 
> > 麻烦将自定义的agent发我看下
> 
> `Mozilla/5.0 (Linux; Android 7.0; KNT-UL10 Build/HUAWEIKNT-UL10) AppleWebKit/537.36 (KHTML, like Gecko) ting_1.8.30(KNT-UL10,Android24)`

可以啦，再试一下

哈哈，裸写代码，肉眼执行，果然不靠谱

**Comment by MisterGlasses** [comment]
> > > > > > 感谢报错，已修复
> > > > > > 大佬第二账号不执行 麻烦看下
> > > > > > https://github.com/MisterGlasses/MyActions/runs/1285954385?check_suite_focus=true
> > > > 
> > > > 
> > > > File "./execute1.py", line 44
> > > > ^
> > > > SyntaxError: invalid syntax
> > > > 同步文件中...
> > > > 文件同步完毕, 处理中...
> > > > HOURS:-1
> > > > 未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
> > > > HOURS:-1
> > > > 未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
> > > > 文件全部执行完毕
> > > 
> > > 
> > > 麻烦将自定义的agent发我看下
> > 
> > 
> > `Mozilla/5.0 (Linux; Android 7.0; KNT-UL10 Build/HUAWEIKNT-UL10) AppleWebKit/537.36 (KHTML, like Gecko) ting_1.8.30(KNT-UL10,Android24)`
> 
> 可以啦，再试一下
> 
> [679a2d0](https://github.com/sazs34/MyActions/commit/679a2d0c92cad72a8cb00d7350f126fc1260bb98)
> 
> 哈哈，裸写代码，肉眼执行，果然不靠谱

https://github.com/MisterGlasses/MyActions/runs/1286274929?check_suite_focus=true
脚本结尾这样正常吗？
同步文件中...

文件同步完毕, 处理中...
HOURS:-1
未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制
HOURS:-1
未配置XMLY_ACCUMULATE_HOURS,因此不会对执行时长进行限制

***************************
文件全部执行完毕

**Comment by sazs34** [comment]
正常的，这是按照顺序返回的执行说明
