### ISSUE TITLE
建议删掉星推官脚本

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#91]
建议删掉星推官脚本，这个脚本是先到先得，现在云端跑了40多分钟还没跑完，可以直接使用手机跑，100秒完成。
此外，这脚本运行时，京东app里点什么都是空白，其它脚本诸如紧跟该脚本的京小超怕是也会受影响。

**Comment by leecheng310** [comment]
手机怎么跑，求教

**Comment by MisterGlasses** [comment]
> 手机怎么跑，求教

GitHub上看一下lxk0301大佬的项目

**Comment by lonma** [comment]
> > 手机怎么跑，求教
> 
> GitHub上看一下lxk0301大佬的项目

大佬，有免费的box下载么

**Comment by leecheng310** [comment]
苹果的圈⭕ 吗，安卓有没什么方案能跑的

**Comment by lonma** [comment]
> > 手机怎么跑，求教
> 
> GitHub上看一下lxk0301大佬的项目

如何去掉内置的助力码？
