### ISSUE TITLE
喜马拉雅刷时长问题

### ISSUE THREAD

**Issue by yellowOld** [sazs34/MyActions#95]
喜马拉雅刷时长那个，我填入了XMLY_ACCUMULATE_TIME以及zero_s1的值，XMLY_ACCUMULATE_HOURS也填入了 “8”。XMLY_ACCUMULATE_INDEX没有填，只有一个账号。为什么执行的时候说是禁用了呢？
![image](https://user-images.githubusercontent.com/42842744/96949452-7919d080-151a-11eb-93c6-43a5efa681d4.png)

**Comment by sazs34** [comment]
36450秒,10个小时了
你设置的时长任务是8小时
自然就禁用后续的时长任务了
