### ISSUE TITLE
喜马拉雅疑问

### ISSUE THREAD

**Issue by yellowOld** [sazs34/MyActions#97]
你好。请问今天为什么好多数字都被***码掉了？昨天没有这情况，然后阅读提示无法阅读的问题。是一定要配置
XMLY_ANDROID_AGENT吗？不是默认有红米8？

![image](https://user-images.githubusercontent.com/42842744/97065429-cd3ab880-15df-11eb-8df1-f3d75cd64796.png)

**Comment by sazs34** [comment]
actions的输出会针对secerts中的值进行替换

然后目前阅读只有安卓端有,需要手动开启才行

**Comment by yellowOld** [comment]
你好。安卓端登录也没看到哪里可以开启呢！可以详细说一下吗？感谢
